Mc1.16/fabric/issue templates
Fabricators-of-Create/Create pull request #5
Opened 2021-03-19 14:05 UTC by YTG1234

For some reason GitHub closed #4.

2021-03-20 20:20 UTC, PepperCode1 requested changes

2021-03-20 20:20 UTC, PepperCode1 commented on .github/ISSUE_TEMPLATE/bug-report.md
> +## System information (please complete the following information):
I think non-JiJed dependency versions and a list of other mods should be provided as well. Someone could report that connected textures don't work with Sodium, but that is not Create's bug.

2021-03-21 05:02 UTC, PepperCode1 approved these changes

2021-03-21 05:28 UTC, TropheusJ commented
add a section under System Information for an alt + shift + f3 debug screenshot. otherwise looks good to me.

2021-04-04 05:41 UTC, PepperCode1 requested changes
Added LBA version and list of other mods. After this change this PR should probably be merged.

2021-04-04 05:41 UTC, PepperCode1 commented on .github/ISSUE_TEMPLATE/bug-report.md
> + - Cloth Config 2 version [e.g. `4.11.14`]
```suggestion
- LibBlockAttributes version [eg. `0.8.4`]
 - Cloth Config 2 version [e.g. `4.11.14`]
```

2021-04-04 05:41 UTC, PepperCode1 commented on .github/ISSUE_TEMPLATE/bug-report.md
> +
```suggestion
- List of all other installed mods, including versions

```

2021-04-04 07:32 UTC, YTG1234 commented on .github/ISSUE_TEMPLATE/bug-report.md
> + - Cloth Config 2 version [e.g. `4.11.14`]
oh wait you missed a space there

2021-04-04 18:41 UTC, PepperCode1 approved these changes

2021-04-04 18:43 UTC, merged